# Generated by Django 5.0.7 on 2024-08-02 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='user_id',
            new_name='writer',
        ),
    ]
