# Generated by Django 5.0.7 on 2024-07-28 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='liked',
            field=models.BooleanField(default=False),
        ),
    ]
